name: CI

on: push
  
jobs:
  test_conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add conda to system path
        run: |
          # $CONDA is apparently an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml
      - name: Will this work
        run: |
          conda list
      - name: Run a test bash script
        run: |
          source test.sh
      - name: Pack env
        run: |
          conda-pack --name coffea-env --output coffea-env.tar.gz
      - name: Start worker
        run: |
          work_queue_worker -d all -o worker.log localhost 9123 &
      - name: Run processor
        run: |
          python coffea-test.py
